//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDirectXDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameDirectXDemo.GameResource", typeof(GameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ActionScreen {
            get {
                object obj = ResourceManager.GetObject("ActionScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Assault {
            get {
                object obj = ResourceManager.GetObject("Assault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cRedit {
            get {
                object obj = ResourceManager.GetObject("cRedit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cursor {
            get {
                object obj = ResourceManager.GetObject("Cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Defender {
            get {
                object obj = ResourceManager.GetObject("Defender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desc {
            get {
                object obj = ResourceManager.GetObject("desc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EXIT {
            get {
                object obj = ResourceManager.GetObject("EXIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fight_button {
            get {
                object obj = ResourceManager.GetObject("Fight_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HowToPlay {
            get {
                object obj = ResourceManager.GetObject("HowToPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap incr {
            get {
                object obj = ResourceManager.GetObject("incr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LevelBg {
            get {
                object obj = ResourceManager.GetObject("LevelBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [header]
        ///width=16
        ///height=12
        ///
        ///[layer]
        ///type=background
        ///data=
        ///33,34,35,15,15,33,34,35,38,48,47,48,47,48,47,48,
        ///33,34,35,15,15,33,34,35,39,31,32,31,32,31,32,31,
        ///33,34,35,15,15,33,34,35,38,39,38,39,38,39,38,39,
        ///33,34,35,15,15,33,34,44,26,26,26,26,26,26,26,26,
        ///33,34,35,15,15,33,34,34,34,34,34,34,34,34,34,34,
        ///33,34,35,15,15,41,42,42,42,42,42,42,42,42,42,42,
        ///33,34,35,15,15,15,15,15,15,15,15,15,15,15,15,15,
        ///33,34,35,15,15,15,15,15,15,15,15,15,15,15,15,15,
        ///33,34,44,26,26,26,26,26,26,26,26,26,26,26,26,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map1 {
            get {
                return ResourceManager.GetString("map1", resourceCulture);
            }
        }
        
        internal static byte[] map11 {
            get {
                object obj = ResourceManager.GetObject("map11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [header]
        ///width=18
        ///height=18
        ///
        ///[layer]
        ///type=background
        ///data=
        ///34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,
        ///34,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,34,
        ///34,30,31,31,31,31,31,31,31,31,31,31,31,31,31,31,30,34,
        ///34,30,31,38,38,38,38,38,38,38,38,38,38,38,38,31,30,34,
        ///34,30,31,38,47,47,47,47,47,47,47,47,47,47,38,31,30,34,
        ///34,30,31,38,47,32,32,32,32,32,32,32,32,47,38,31,30,34,
        ///34,30,31,38,47,32,46,46,46,46,46,46,32,47,38,31,30,34,
        ///34,30,31,38,47,32,46,39,39,39,39,46,32,47,38,31,30,34, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map2 {
            get {
                return ResourceManager.GetString("map2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [header]
        ///width=36
        ///height=24
        ///
        ///[layer]
        ///type=background
        ///data=
        ///46,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,31,30,
        ///30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,31,30,30,30,30,30,30,30,30,31,31,31,31,30,
        ///30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,34,34,30,30,30,30,30,31,31,30,30,30,30,30,30,30,31,31,31,30,30,
        ///30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,34,34,30,30,30,30,30,31,31,31,31,31,31,31,31,31,31,31,31,31,30,
        ///38,38, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map3 {
            get {
                return ResourceManager.GetString("map3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MenuScreen {
            get {
                object obj = ResourceManager.GetObject("MenuScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mouse_cursor {
            get {
                object obj = ResourceManager.GetObject("mouse_cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewGame {
            get {
                object obj = ResourceManager.GetObject("NewGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ranger {
            get {
                object obj = ResourceManager.GetObject("Ranger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap robot {
            get {
                object obj = ResourceManager.GetObject("robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tittle {
            get {
                object obj = ResourceManager.GetObject("tittle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
